# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.7.0
_src_path: gh:radio-aktywne/template-generic
accountname: radio-aktywne
description: NixOS configs for our machines ❄️
docs: true
docsurl: https://radio-aktywne.github.io/systems
projectname: systems
releases: false
reponame: systems
repourl: https://github.com/radio-aktywne/systems
